/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abojawdat;

import java.awt.print.PrinterException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mohammed A Mahjoub
 */
public class aboJawdat extends javax.swing.JFrame {

    /**
     * Creates new form aboJawdat
     */
    public aboJawdat() {
        initComponents();
        // 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        mobile = new javax.swing.JTextField();
        mNo = new javax.swing.JTextField();
        quantity = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        notes = new javax.swing.JTextField();
        print = new javax.swing.JButton();
        save = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name.setBackground(new java.awt.Color(162, 132, 11));
        name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 200, 30));

        jTextArea.setEditable(false);
        jTextArea.setBackground(new java.awt.Color(162, 132, 11));
        jTextArea.setColumns(20);
        jTextArea.setLineWrap(true);
        jTextArea.setRows(5);
        jTextArea.setToolTipText("");
        jTextArea.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jScrollPane3.setViewportView(jTextArea);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 140, 370, 380));

        mobile.setBackground(new java.awt.Color(162, 132, 11));
        mobile.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 200, 30));

        mNo.setBackground(new java.awt.Color(162, 132, 11));
        mNo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(mNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 200, 30));

        quantity.setBackground(new java.awt.Color(162, 132, 11));
        quantity.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 200, 30));

        price.setBackground(new java.awt.Color(162, 132, 11));
        price.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 200, 30));

        notes.setBackground(new java.awt.Color(162, 132, 11));
        notes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        getContentPane().add(notes, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 200, 30));

        print.setForeground(new java.awt.Color(25, 255, 25));
        print.setText("طباعة");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        getContentPane().add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 540, 150, 40));

        save.setForeground(new java.awt.Color(25, 255, 25));
        save.setText("حفظ");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 540, 150, 40));

        clear.setForeground(new java.awt.Color(25, 255, 25));
        clear.setText("جديد");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 540, 150, 40));

        back.setForeground(new java.awt.Color(25, 255, 25));
        back.setText("back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 610, 150, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abojawdat/WhatsApp Image 2021-01-25 at 8.56.54 PM.jpeg"))); // NOI18N
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents
 Database db = new Database();
    Date dd = new Date();
    SimpleDateFormat sfd = new SimpleDateFormat("MM/dd/yyyy");
    SimpleDateFormat sft = new SimpleDateFormat("hh:mm:ss");
    SimpleDateFormat sf = new SimpleDateFormat("EEEEEEEEEE");
    DefaultTableModel model;
    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
        try {
            jTextArea.print();
        } catch (PrinterException ex) {
            Logger.getLogger(aboJawdat.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_printActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
         db.add(name.getText(), mobile.getText(), mNo.getText(), quantity.getText(), price.getText(), sfd.format(dd), sf.format(dd), sft.format(dd), notes.getText());
        jTextArea.setText("\n\n\tمعصرة الزيت الأخضر الإيطالية الحديثة\n"
                + "\n================================================\n\t"
                + "\n\t\t" + db.getCounter() + "\n"
                + "                  " + name.getText() + "\t\tالاسم\n"
                + "                  " + mobile.getText() + "\t\tرقم الجوال\n\t"
                + mNo.getText() + "\t\tرقم المخال\n\t"
                + quantity.getText() + "\t\tالكمية \n\t"
                + price.getText() + "\t\t السعر\n\t"
                + sfd.format(dd) + "\t\tالتاريخ\n\t"
                + sf.format(dd) + "\t\tاليوم\n\t"
                + sft.format(dd) + "\t\t الساعة\n"
                + "\n\t\tملاحظات"
                + "\n================================================\n\t\t"
                + notes.getText()
        );
    }//GEN-LAST:event_saveActionPerformed
login l = new login();
    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        name.setText("");
        mobile.setText("");
        mNo.setText("");
        quantity.setText("");
        price.setText("");
        notes.setText("");
        jTextArea.setText("");
    }//GEN-LAST:event_clearActionPerformed
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(aboJawdat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(aboJawdat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(aboJawdat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(aboJawdat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new aboJawdat().setVisible(true);
//            }
//        });
//        Database.connect();
//        Database.getLastIndex();
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton clear;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JTextField mNo;
    private javax.swing.JTextField mobile;
    private javax.swing.JTextField name;
    private javax.swing.JTextField notes;
    private javax.swing.JTextField price;
    private javax.swing.JButton print;
    private javax.swing.JTextField quantity;
    private javax.swing.JButton save;
    // End of variables declaration//GEN-END:variables
}
